# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_hw')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_hw')
    _hw = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hw', [dirname(__file__)])
        except ImportError:
            import _hw
            return _hw
        try:
            _mod = imp.load_module('_hw', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _hw = swig_import_helper()
    del swig_import_helper
else:
    import _hw
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class HelloWorld(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HelloWorld, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HelloWorld, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _hw.new_HelloWorld()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _hw.delete_HelloWorld
    __del__ = lambda self: None

    def set(self, r1: 'double', r2: 'double') -> "void":
        return _hw.HelloWorld_set(self, r1, r2)

    def get(self) -> "double":
        return _hw.HelloWorld_get(self)

    def message(self, out: 'std::ostream &') -> "void":
        return _hw.HelloWorld_message(self, out)

    def print_(self) -> "void":
        return _hw.HelloWorld_print_(self)
HelloWorld_swigregister = _hw.HelloWorld_swigregister
HelloWorld_swigregister(HelloWorld)

class HelloWorld2(HelloWorld):
    __swig_setmethods__ = {}
    for _s in [HelloWorld]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HelloWorld2, name, value)
    __swig_getmethods__ = {}
    for _s in [HelloWorld]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, HelloWorld2, name)
    __repr__ = _swig_repr

    def gets(self) -> "void":
        return _hw.HelloWorld2_gets(self)

    def __init__(self):
        this = _hw.new_HelloWorld2()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _hw.delete_HelloWorld2
    __del__ = lambda self: None
HelloWorld2_swigregister = _hw.HelloWorld2_swigregister
HelloWorld2_swigregister(HelloWorld2)

# This file is compatible with both classic and new-style classes.


